# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/2y2ssn/CLionProjects/cpp/src/leetcode/CMakeLists.txt))

/Users/2y2ssn/CLionProjects/cpp/cpp_build_Xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.18.1/bin/cmake -H/Users/2y2ssn/CLionProjects/cpp -B/Users/2y2ssn/CLionProjects/cpp/cpp_build_Xcode
